# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8bc0c59cee093872cd12c05be8125b00353b6b3efc3f3b0c9dde12cfb8edd736c4fa4d2a8fd3741c7d37a04fb3922ba5017bb610a8a997b81c011ffc0a83ab57

test:
  secret_key_base: 24c5e15b84862c3448832eba12423cf37ef488a9dca6cca4ed4925540906c4641d29135ddf355e6c77cc4951bcef425462ae55162e6d0ac9fd990728a03a6f94

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
